//variables

const person = document.querySelector('.person');
const quote = document.querySelector('.quote');
const btn = document.querySelector('#new-quote')

let quotes = [
    {
        quote: "It takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you'll do things differently.",
        person:'Warren Buffett'
    },
    {
        quote:"If you love life, don’t waste time, for time is what life is made up of.",
        person:'Bruce Lee'
    },
    {
        quote:"Don’t settle for what life gives you; make life better and build something.",
        person:'Ashton Kutcher'
    },
    {
        quote: "Do all the good you can, for all the people you can, in all the ways you can, as long as you can.",
        person:'Hilary Clinton'
    },
    {
        quote:"Your time is limited, so don’t waste it living someone else’s life. Don’t be trapped by dogma .",
        person:'Steve Jobs'
    },
    {
        quote: "Money and success don’t change people; they merely amplify what is already there.",
        person:'Will Smith'
    },
    {
        quote:"If you want to live a happy life, tie it to a goal, not to people or things.",
        person:'Albert Einstein'
    },
    {
        quote:"Life is what happens when you're busy making other plans." ,
        person:'John Lenon'
    },
    {
        quote:"You only live once, but if you do it right, once is enough.",
        person:'Mae West'
    },
    {
        quote:"Get busy living or get busy dying.",
        person: 'Stephen King'
    },
    {
        quote:"As you grow older, you will discover that you have two hands, one for helping yourself, the other for helping others.",
        person: 'Audrey Hepburn'
    },
    {
        quote:"Humanity is an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty.",
        person: 'Mahatma Gandhi'
    }
]

btn.addEventListener('click', func);
function func(){
    let random = Math.floor(Math.random() * quotes.length);   //math.random does not generate a whole number, hence it is put in the math.floor which will round the number generated by math.number to a wholw number

    quote.innerText = quotes[random].quote;          //will print the texts of the quote for the random number generated
    person.innerText = quotes[random].person;         //will print the corresponding text of the name
}

